import type { Product } from "../types/index.ts";
        import { mockFarms } from "./mockFarms.ts";

        export const mockProducts: Product[] = [
            {
                id: 1,
                category: 'Diary',
                title: 'Yogurt',
                description: 'Fresh yogurt',
                amount: 20,
                price: 3,
                units: 'kg',
                farm: mockFarms[0], // Ссылка на объект фермы
                imageUrl: '/src/assets/yogurt.jpg',
            },
            {
                id: 2,
                category: 'Fruits',
                title: 'Oranges',
                description: 'Fresh oranges',
                amount: 30,
                price: 4,
                units: 'kg',
                farm: mockFarms[1],
                imageUrl: '/src/assets/orange.jpg',
            },
            {
                id: 3,
                category: 'Vegetables',
                title: 'Tomatoes',
                description: 'Fresh tomatoes',
                amount: 100,
                price: 2.5,
                units: 'kg',
                farm: mockFarms[2],
                imageUrl: '/src/assets/tomat.jpg',
            },
            {
                id: 4,
                category: 'Diary',
                title: 'Cheese',
                description: 'Fresh cheese',
                amount: 200,
                price: 26,
                units: 'kg',
                farm: mockFarms[3],
                imageUrl: '/src/assets/cheese.jpg',
            },
            {
                id: 5,
                category: 'Pantry',
                title: 'Honey',
                description: 'Fresh honey',
                amount: 88,
                price: 60,
                units: 'kg',
                farm: mockFarms[4],
                imageUrl: '/src/assets/honey.jpg',
            },
            {
                id: 6,
                category: 'Herbs',
                title: 'Roses',
                description: 'Fresh roses',
                amount: 88,
                price: 20,
                units: 'jar',
                farm: mockFarms[5],
                imageUrl: '/src/assets/rose.jpg',
            },
            {
                id: 7,
                category: 'Herbs',
                title: 'Basil',
                description: 'Fresh basil',
                amount: 88,
                price: 20,
                units: 'kg',
                farm: mockFarms[6],
                imageUrl: '/src/assets/basil.jpg',
            },
            {
                id: 8,
                category: 'Vegetables',
                title: 'Cucumbers',
                description: 'Fresh cucumbers',
                amount: 100,
                price: 2.5,
                units: 'kg',
                farm: mockFarms[0],
                imageUrl: '/src/assets/cucumber.jpg',
            },
            {
                id: 9,
                category: 'Herbs',
                title: 'Mint',
                description: 'Fresh mint',
                amount: 88,
                price: 20,
                units: 'kg',
                farm: mockFarms[1],
                imageUrl: '/src/assets/mint.jpg',
            },
            {
                id: 10, // Исправлено: уникальный id
                category: 'Fruits',
                title: 'Avocado',
                description: 'Fresh avocado',
                amount: 30,
                price: 4,
                units: 'kg',
                farm: mockFarms[2],
                imageUrl: '/src/assets/avocado.jpg',
            },
        ];